### ISSUE TITLE
epinio-install helm chart is tested and works

### ISSUE THREAD

**Issue by jimmykarily** [epinio/helm-charts#16]
Work is happening here: https://github.com/epinio/epinio-helm-chart/pull/13

It should work using `helm` cli but also on Rancher.

**Comment by juadk** [comment]
- [ ] Epinio is installing well on top of Rancher with epinio-installer helm chart and the following options:

![rancher_install](https://user-images.githubusercontent.com/6025636/146019973-32b08241-63c5-45ce-bcbd-c13f92e75fed.png)

- [ ] Deploying an app with CLI worked well but deploying through the Webui stuck in the last step.

**Comment by ldevulder** [comment]
## My setup

### Rancher and Epinio in a K3s cluster:
- [ ] Epinio installed on top of Rancher with epinio-installer helm chart and the default options
- [ ] Epinio installed on `epinio-install` namespace
- [ ] Deploying an app with CLI
- [ ] Uninstall Epinio
- [ ] Customize API user / password
- [ ] Installation with external registry
- [ ] Installation with S3 storage
- [ ] Installation with Letsencrypt and/or custom CA, however, it's not possible to deploy an app due to #37 not released yet

### Rancher and Epinio in a RKE2 cluster:
- [ ] Epinio installed on top of Rancher with epinio-installer helm chart and the default options
- [ ] Epinio installed on `epinio-install` namespace
- [ ] Deploying an app with CLI
- [ ] Uninstall Epinio
- [ ] Customize API user / password
- [ ] Installation with external registry
- [ ] Installation with S3 storage
- [ ] Installation with Letsencrypt and/or custom CA, however, it's not possible to deploy an app due to #37 not released yet

**Comment by juadk** [comment]
Release is done, I think we need to summarize the tests we did on a confluence page before starting the automation with Cypress. We will need to do the same with the upgrade feature.
That means, 3 things are pending on Cypress:
- UI
- Helm installation
- Upgrade
@prabalsharma WDYT?

**Comment by prabalsharma** [comment]
@juadk sounds about right. We can summarize these tests cases on confluence and take it from there. 
By "Helm installation on Cypress", you mean automating Epinio installation via Rancher Dashboard, correct?

**Comment by juadk** [comment]
> By "Helm installation on Cypress", you mean automating Epinio installation via Rancher Dashboard, correct?

Yes, correct.
