### ISSUE TITLE
Access Control url could be simplified

### ISSUE THREAD

**Issue by agracey** [epinio/helm-charts#71]
When accessControlAllowOrigin is not passed in, we could default to the same value as `common.global.cattle.url`. When installed via Rancher, this value is the hostname that Rancher knows about itself.

**Comment by juadk** [comment]
Very good point! Moreover, accessControlAllowOrigin is not so user-friendly.

**Comment by jimmykarily** [comment]
@agracey what is `common.global.cattle.url`? Where is it defined?

**Comment by agracey** [comment]
It's injected into the values by Rancher when you install a chart via the UI. You define it when you install Rancher itself.

**Comment by agracey** [comment]
I don't know about if Fleet or other ways of installing charts add the same or similar. 

It shouldn't be the only way we allow defining the value but could likely be the default.

**Comment by andreas-kupries** [comment]
@richard-cox Is this still relevant for the UI ? @thehejik proposes to remove the item from question.yml entirely.
Not clear if our integration with the Marketplace would be affected.

**Comment by richard-cox** [comment]
If memory serves it's to support browser requests from one domain to another. That only affects the epinio ui when it's embedded into the rancher dashboard. That part isn't currently working due to auth changes and has probably suffered some major bit rot. Hopefully it should come back one day though. I propose

- It remains in questions.yaml but is optional
- The chart uses `common.global.cattle.url` but falls back on the epinio domain (might be doing that latter already)
